version: '3.9'

services:
  ndros:
    tty: true
    ipc: host
    privileged: true
    container_name: ndros-dev
    image: ndros
    build:
      context: .
      dockerfile: docker/foxy.Dockerfile
    security_opt:
      - seccomp:unconfined
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all # or device number (e.g. 0) to allow a single gpu
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: ${DISPLAY} # Add this line if you are using a Linux desktop
      QT_X11_NO_MITSHM: 1

    cap_add:
      - CAP_SYS_ADMIN # Add this line

    ports:
      - "6006:6006"

    expose:
      - 6006

    volumes:
      - .:/workspace/Project1
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input:/dev/input